[tool.pylint]

[tool.pylint.messages_control]
# Disable the message, report, category or checker with the given id(s).
disable = [
    "empty-docstring",  # Let docformatter and ruff take care of docstrings
    "logging-fstring-interpolation",  # f-strings are convenient
    "missing-docstring",  # Let docformatter and ruff take care of docstrings
    "too-few-public-methods",  # Don't care to enforce this
    "too-many-arguments",  # Don't care to enforce this
    "ungrouped-imports",  # Rely on isort for this
    "unsubscriptable-object",  # Buggy, SEE: https://github.com/PyCQA/pylint/issues/3637
    "unused-wildcard-import",  # Wildcard imports are convenient
    "wildcard-import",  # Wildcard imports are convenient
    "wrong-import-order",  # Rely on isort for this
]
# Enable the message, report, category or checker with the given id(s).
enable = [
    "useless-suppression",  # Print unused `pylint: disable` comments
]

[tool.pylint.reports]
# Set true to activate the evaluation score.
score = false

[tool.tomlsort]
all = true
in_place = true
spaces_before_inline_comment = 2  # Match Python PEP 8
spaces_indent_inline_array = 4  # Match Python PEP 8
trailing_comma_inline_array = true
