---
name: Lint and test Python

on: # yamllint disable-line rule:truthy
  pull_request:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          cache: "pip"
      - run: python -m pip install -r requirements.txt
      - uses: pre-commit/action@v3.0.0
      - run: pytest
